from pytube import YouTube,Playlist,exceptions
import sys
import os
from moviepy.editor import *

class YTAudioDownload():
    """
    Youtube auto generated playlist do not work, cant extract videos from it
    if 410 error, might need pytube update

    """

    def __init__(self,path="/home/piaxis/Music/"):#change that
        self.path=path
        self.failed=[]

    def _dl_from_yt_object(self,yt):
        file=yt.streams.get_audio_only().download(self.path)
        video = AudioFileClip(file)
        video.write_audiofile(file[:-1]+"3")
        os.remove(file)
  
    
    def dl(self,url):
        yt=YouTube(url)    
        self._dl_from_yt_object(yt)

    def dl_from_playlist(self,url_playlist):
        plist=Playlist(url_playlist)
        print(f"length of playlist: {plist.length}")
        for count,yt in enumerate(plist.videos):
            try:
                self._dl_from_yt_object(yt)
                print(f"done video {count+1} ")


            except exceptions.AgeRestrictedError:
                print("Age restricted")
                self.failed.append(yt.title)

            except Exception as e:
                print(f"other exception: {e}")
                self.failed.append(yt.title)

        print(self.failed)



if __name__=="__main__":
    """ 
    need to put brackets around url to download "https://www.youtube.com/watch?v=DhU10tZxVuda" 
    autogenerated playlist do not work
    """

    url=sys.argv[1]

    try:
        path=sys.argv[2]
        YT=YTAudioDownload(path)
    except:
        YT=YTAudioDownload()

    if "list=" in url:
        print("Downloading playlist: " + url)
        YT.dl_from_playlist(url)
        
    else:
        print("Downloading video: "+url)
        YT.dl(url)
